version: '3.1'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hellodemo
      - MYSQL_USER=hellouser
      - MYSQL_PASSWORD=secret