insert into hellodemo.Professor (name, surname)
values ('Bart', 'Vanrumste'),
       ('Koen', 'Pelsmaekers'),
       ('Jeroen', 'Vanaken'),
       ('Vero', 'Vandenabeele'),
       ('Kathrin', 'Gerling'),
       ('Luc', 'Geurts'),
       ('Toon', 'Van Waterschoot'),
       ('Josep', 'Balasch Masoliver'),
       ('Yuri', 'Cauwerts'),
       ('Hannes', 'Rosseel'),
       ('Hannelore', 'Strauven'),
       ('Kymeng', 'Tang'),
       ('Jeroen', 'Wauters'),
       ('Geert', 'Waeyenbergh'),
       ('Wim', 'De Roeck'),
       ('Jeroen', 'De Nève'),
       ('Koen', 'Riemis'),
       ('Inge', 'Holsbeeks'),
       ('Laura', 'Gobbens'),
       ('Wouter', 'Meynendonckx'),
       ('Gert', 'Van Loock'),
       ('Cedric', 'Debien'),
       ('Stijn', 'Langendries'),
       ('Gorik', 'Stevens'),
       ('Ruben', 'Vanhoof'),
       ('Gil', 'Vranken'),
       ('Wim', 'Van Petegem'),
       ('Ludo', 'Bruynseels'),
       ('Arnor', 'Van Leemputten');


